FROM ubuntu:18.04

LABEL MAINTAINER=theazurelab@gmail.com

# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update \
        && apt-get install -y --no-install-recommends \
        wget \
        ca-certificates \
        curl \
        jq \
        git \
        iputils-ping \
        libcurl4 \
        libicu60 \
        libunwind8 \
        netcat \
        libssl1.0 

# Download the Microsoft repository GPG keys
RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

# Register the Microsoft repository GPG keys
RUN dpkg -i packages-microsoft-prod.deb

# Setup powershell
RUN apt-get update \
        && apt-get install -y --no-install-recommends \
        apt-transport-https \
        software-properties-common \
        powershell

# Enable the 'universe' repositories
RUN add-apt-repository universe

RUN pwsh -c "Install-Module -Name PowerShellGet -Force"

# Install the latest rollup
RUN pwsh -c "Install-Module -Name Az -AllowClobber -Force"

# Import the latest version
RUN pwsh -c "Import-Module Az"

# Install kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
        && chmod +x ./kubectl \
        && mv ./kubectl /usr/local/bin/kubectl

# Install bicep
RUN curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64 \
        && chmod +x ./bicep \
        && mv ./bicep /usr/local/bin/bicep

# Install the Azure CLI
RUN apt-get update && curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Clean system
RUN apt-get clean \
        && rm -rf /var/lib/apt/lists/* \
        && rm -rf /etc/apt/sources.list.d/*

WORKDIR /azp